### PR TITLE
Refactored secure base_url logic

### LINKED ISSUE #91: Cookie Not Marked As Secure in Frontend with SSL e
My client did a pentest and found a vulnerability on session hijacking attack:

**_start**_
A Cookie was not marked as secure and transmitted over HTTPS. This means the cookie could potentially be stolen by an attacker who can successfully intercept and decrypt the traffic or following a successful MITM (Man in the middle) attack.

This cookie will be transmitted over a HTTP connection, therefore if this cookie is important (such as a session cookie) an attacker might intercept it and hijack a victim's session. If the attacker can carry out a MITM attack, he/she can force victim to make a HTTP request to steal the cookie.
**_end**_

This issue was reported in the forum: http://www.magentocommerce.com/boards/viewthread/11073/#t160609

Code Analysis:
line 178 in class Mage_Core_Model_Cookie::isSecure()
/**
- Is https secure request
- Use secure on adminhtml only
  *
- @return bool
  */
  public function isSecure()
  {
  if ($this->getStore()->isAdmin()) {
  return $this->_getRequest()->isSecure();
  }
  return false;
  }

In order to pass the pentest, isSecure() has to include frontend, therefore the code should just be
public function isSecure()
{ 
return $this->_getRequest()->isSecure(); 
}

 Join the Dialogue|3 comments
1kiatng|posted 1 day ago

There is a problem with my suggested workaround: it'll mess up the frontend session. Is there another way around this? Please advise as I need to revert to my client. Thanks.
2thebod|posted 1 day ago

Hey, please check out my answer here: http://www.magentocommerce.com/boards/viewthread/283764/
3Magento Team|posted 14 hours ago

Hello kiatng,

Yes, suggested workaround will not work.
Once again, Magento uses both HTTP and HTTPS on frontend (and we are not planning to change it) that is why there is no general solution. Cookie is transfered without 'secure' flag to be accessible under both HTTPS and HTTP.

Currently we have closed this ticket.
You have to accept the risk related to possible MITM attack (as it is minor in case of Magento).

Thank you for understanding.

imported from : http://www.magentocommerce.com/bug-tracking/issue?issue=13768

### PR DESCRIPTION
**Pull request by tux-rampage**
As discussed: The last implementation may confuse users. See pull request #96 for details.
Refactored logics to the following solution:
- Merged second config option to secure the entire store into
  use_in_frontend
- Added source model for use secure base_url in frontend option

Resolves #91
Please review and pull if acceptable.

### CODE REVIEW

**Comment by tux-rampage** [comment]
Hi, is there any reason for not merging this to master or dev?

**Comment by leesbian** [comment]
I haven't had time to review the fix yet - will do so this weekend, and merge to master if it's all OK

**Comment by tux-rampage** [comment]
Hi Lee,

is there a reason for not pulling these changes?
Does it need further changes?

**Comment by tux-rampage** [comment]
This project seems to be dead. I am closing this request to clean up my profile.

**Pull request closed without merging**
