### PR TITLE
[+BUGFIX] Added option to use secure urls for all store pages

### LINKED ISSUE #91: Cookie Not Marked As Secure in Frontend with SSL e
My client did a pentest and found a vulnerability on session hijacking attack:

**_start**_
A Cookie was not marked as secure and transmitted over HTTPS. This means the cookie could potentially be stolen by an attacker who can successfully intercept and decrypt the traffic or following a successful MITM (Man in the middle) attack.

This cookie will be transmitted over a HTTP connection, therefore if this cookie is important (such as a session cookie) an attacker might intercept it and hijack a victim's session. If the attacker can carry out a MITM attack, he/she can force victim to make a HTTP request to steal the cookie.
**_end**_

This issue was reported in the forum: http://www.magentocommerce.com/boards/viewthread/11073/#t160609

Code Analysis:
line 178 in class Mage_Core_Model_Cookie::isSecure()
/**
- Is https secure request
- Use secure on adminhtml only
  *
- @return bool
  */
  public function isSecure()
  {
  if ($this->getStore()->isAdmin()) {
  return $this->_getRequest()->isSecure();
  }
  return false;
  }

In order to pass the pentest, isSecure() has to include frontend, therefore the code should just be
public function isSecure()
{ 
return $this->_getRequest()->isSecure(); 
}

 Join the Dialogue|3 comments
1kiatng|posted 1 day ago

There is a problem with my suggested workaround: it'll mess up the frontend session. Is there another way around this? Please advise as I need to revert to my client. Thanks.
2thebod|posted 1 day ago

Hey, please check out my answer here: http://www.magentocommerce.com/boards/viewthread/283764/
3Magento Team|posted 14 hours ago

Hello kiatng,

Yes, suggested workaround will not work.
Once again, Magento uses both HTTP and HTTPS on frontend (and we are not planning to change it) that is why there is no general solution. Cookie is transfered without 'secure' flag to be accessible under both HTTPS and HTTP.

Currently we have closed this ticket.
You have to accept the risk related to possible MITM attack (as it is minor in case of Magento).

Thank you for understanding.

imported from : http://www.magentocommerce.com/bug-tracking/issue?issue=13768

### PR DESCRIPTION
**Pull request by tux-rampage**
Added option to turn on SSL for all frontend pages to system.xml.
This option will also flag frontend cookies secure.
Added a comment to web/secure/use_in_frontend because there are
pitfalls.

Resolves #91

Please review and pull if accepted

### CODE REVIEW

**Comment by tux-rampage** [comment]
It fixes #91

That means all frontend pages will use the secure base_url and cookies will be flagged secure as in admin panel.

EDIT:
It allows to make a difference between:
- All frontend pages use HTTPS (New - For max security)
- Only pages with sensitive information use https (login, account, checkout, etc ...) and the rest is using http (The Default of Magento - For better performance)

The new Option requires the existing option "general > web > Use Secure URLs in Frontend" to be set to "Yes". If it is set to no, the new option will have no effect. So it enhances the existing functionality for users requiring max security as in Issue #91

I hope this is understandable. I'm no native English speaker, so please accept my apologies if something may be expressed incorrect or confusing. I try my best to explain.

**Comment by leesbian** [comment]
ah OK - it forces all frontend pages to be in https context

my concern here is confusion arising around the 2 similar config options. Possibly a better solution would be to make the existing config option a radio button, so the options are force ALL pages, the existing secure frontend implementation, or off

**Comment by tux-rampage** [comment]
Would it be an option to change the Yes/No Dropdown to a Dropdown with the following options:
- Disabled
- Enabled for pages consuming sensitive user data
- Enabled for all pages

The first two options behave like the current yes/no and the third option forces all pages (and cookies) to be https.

**Comment by leesbian** [comment]
yes, a dropdown would also work

**Comment by tux-rampage** [comment]
All right, I'll open a separate pull request after I've changed this. I am closing this one

**Pull request closed without merging**
