### PR TITLE
Bugfix: Visibility was set to default when updating a product via ImportExport

### PR DESCRIPTION
**Pull request by avstudnitz**
Bugfix for ImportExport: If an attribute column is not given, it is reset to default value on import (i.e. for visibility, most other attributes don't have a default value). Fixed for updating existing products. See http://www.avs-webentwicklung.de/nc/blog/artikel/magento-importexport-der-visibility-bug.html (German only, sorry)

### CODE REVIEW

**Comment by leesbian** [comment]
this has been merged into develop branch (Mage+ v1.1)

**Comment by Zifius** [comment]
@avstudnitz can you please tell where in the code visibility value is reset to default? Just stumbled upon this when saving product collection and visibility attribute is not added to `addAttributeToSelect`. Might be quite common pitfall when updating a bunch of products and some has been hidden

**Comment by avstudnitz** [comment]
@Zifius It's lines 303 to 305 in Mage_ImportExport_Model_Import_Entity_Product_Type_Abstract. See the diff at https://github.com/mageplus/mageplus/pull/95/files. I am not sure if I understood your question correctly.

**Comment by Zifius** [comment]
@avstudnitz Sorry for not being clear Andreas, I'm talking about general case of loading a products collection without adding the visiblity attribute and saving it

**Pull request closed without merging**
