### PR TITLE
split up Mage_All.xml into individual module configurations

### PR DESCRIPTION
**Pull request by leesbian**
removed Mage_All.xml, put the configurations for each module into their own configuration files - allows for easier maintainability (and to start easily verifying dependent modules), also allows for end users to more easily disable individual components of Magento

### CODE REVIEW

**Comment by mzeis** [comment]
In my opinion changes like these should not be done in Mageplus. It's neither a bugfix nor a new feature. I do understand what you're trying to achieve but the problem is that you're moving farther away from the core than necessary.

**Comment by fbrnc** [comment]
I fully agree. Mage+ should be as close as possible to the original version. That doesn't mean that new features cannot be added, but merging and comparing to the original version should be easy at every point in time. This commit actually is neither a bugfix nor a real improvement.

Besides that "Mage_All.xml" is somehow hardcoded in the core when it comes to the loading order of the modules. First everything in Mage_All, then Mage_\* and then everything else. Check Mage_Core_Model_Config->_getDeclaredModuleFiles()

Bye, and have a nice day,...

Fabrizio :)

**Comment by leesbian** [comment]
Mage_All.xml is indeed hardcoded - it's a hack because module dependencies are incorrectly declared for the "core" modules, and the way to guarantee the loading order was by forcing Mage_All to load first. We can remedy that hack quite easily - so yes - it's a bugfix :)

Additionally, I don't agree that Mage_All.xml should (for instance) include the Mage_Poll module, or Ratings, or Reviews - that's not core functionality. I've never even seen the Polls module used on any production store. Magento is meant to be modular - as such, (as an implementer) I should be able to pare down Magento as much as I see necessary for each individual implementation. I only want to include the necessary components to make my store work - less code to maintain and better performance

Splitting up the Mage_All.xml is the first step towards making it easier to disable unwanted modules, and to resolving some of the circular dependencies that exist within "core" Magento modules (eg Ratings and Reviews)

**Comment by leesbian** [comment]
.. besides, Magento itself is hardly consistent with it's use of Mage_All - I would argue Mage_Bundle or Mage_Connect are more "core" than Polls, Ratings or Reviews, and yet both have their own module xml

**Comment by fbrnc** [comment]
No doubt, I would prefer if the Magento developers had done it the way you want to do it the first place. Besides that you cannot rely on the configured dependencies, because there are much more hardcoded dependencies inside the modules that are not reflected in the in the xml configuration.

But the question (that we also started discussing in a large group at Meet Magento in Leipzig) is: Where is this Mage+ going to? Is the main goal to improve Magento at any costing breaking upgradability and compability to the version maintained by Magento, Inc? Or do we rather want something like a "better version of Magento", that is close to the original one, grows with the main version and is mainly seen (and thus so much easier adopted) as a community maintained LTS version? A version that developer can contribute their solutions they have been struggling with to and benefit from other having solved those problems before?

**Comment by leesbian** [comment]
Good questions, however, this isn't really the correct place to be discussing these issues

I'll address these issues in a blog post or in the project governance documents that I'm currently putting together

**Comment by leesbian** [comment]
merged into develop branch for v1.1 release

**Pull request closed without merging**
